arguments:
  format: json
git_services:
  - host: github.com
    repos:
      - conforma/community
      - conforma/conforma.github.io
      - conforma/demos
      - conforma/.github
      - conforma/go-gather
      - conforma/hacks
      - conforma/policy
      - conforma/review-rot
      - conforma/tekton-catalog
      - conforma/user-guide
      - enterprise-contract/action-validate-image
      - enterprise-contract/config
      - enterprise-contract/ec-cli
      - enterprise-contract/enterprise-contract-controller
      - enterprise-contract/.github
      - enterprise-contract/github-workflows
      - enterprise-contract/golden-container
      - enterprise-contract/hooks
      - enterprise-contract/infra-deployments-ci
      - enterprise-contract/policy_builder
      - konflux-ci/build-definitions
      - konflux-ci/build-trusted-artifacts
      - konflux-ci/docs
      - konflux-ci/e2e-tests
      - konflux-ci/konflux-ci.github.io
      - konflux-ci/konflux-test
      - konflux-ci/release-service-catalog
      - redhat-appstudio/infra-deployments
      - redhat-appstudio/tssc-sample-templates
      - tektoncd/chains
    token: "${GITHUB_TOKEN}"
    type: github
