arguments:
  format: json
  reverse: True
  categorize_automated: True
git_services:
  - host: github.com
    repos:
      - conforma/.github
      - conforma/action-validate-image
      - conforma/build-definitions
      - conforma/claude-skills
      - conforma/cli
      - conforma/community
      - conforma/config
      - conforma/conforma.github.io
      - conforma/crds
      - conforma/demos
      - conforma/github-workflows
      - conforma/go-containerregistry
      - conforma/go-gather
      - conforma/golden-container
      - conforma/golden-rpm
      - conforma/hacks
      - conforma/hooks
      - conforma/infra-deployments
      - conforma/infra-deployments-ci
      - conforma/knative-service
      - conforma/policy
      - conforma/policy-builder
      - conforma/pr-agent-settings
      - conforma/pr-size-label-action
      - conforma/review-rot
      - conforma/tekton-catalog
      - conforma/user-guide
      - enterprise-contract/enterprise-contract-controller
      - enterprise-contract/.github 
      - konflux-ci/build-definitions
      - konflux-ci/build-trusted-artifacts
      - konflux-ci/docs
      - konflux-ci/e2e-tests
      - konflux-ci/konflux-ci.github.io
      - konflux-ci/konflux-test
      - konflux-ci/release-service-catalog
      - redhat-appstudio/infra-deployments
      - konflux-ci/tektor
      - redhat-appstudio/tssc-dev-multi-ci
      - redhat-appstudio/tssc-sample-templates
      - tektoncd/chains
    token: "${GITHUB_TOKEN}"
    type: github
    labels:
      - "size: XS"
      - "size: S"
      - "size: M"
      - "size: L"
      - "size: XL"
      - "size: XXL"
