arguments:
  format: json
git_services:
- host: github.com
  repos:
  - enterprise-contract/.github
  - enterprise-contract/ec-cli
  - enterprise-contract/user-guide
  - enterprise-contract/ec-policies
  - enterprise-contract/enterprise-contract-controller
  - enterprise-contract/golden-container
  - enterprise-contract/enterprise-contract.github.io
  - enterprise-contract/hacks
  - enterprise-contract/infra-deployments-ci
  - enterprise-contract/tekton-catalog
  - enterprise-contract/config
  - redhat-appstudio/book
  - redhat-appstudio/build-definitions
  - redhat-appstudio/docs.appstudio.io
  - redhat-appstudio/e2e-tests
  - redhat-appstudio/infra-deployments
  #- renovatebot/renovate
  - tektoncd/chains
  token: "${GITHUB_TOKEN}"
  type: github
