arguments:
  format: json
git_services:
  - host: github.com
    repos:
      - conforma/.github
      - conforma/conforma.github.io
      - enterprise-contract/action-validate-image
      - enterprise-contract/community
      - enterprise-contract/config
      - enterprise-contract/ec-cli
      - enterprise-contract/ec-policies
      - enterprise-contract/enterprise-contract-controller
      - enterprise-contract/enterprise-contract.github.io
      - enterprise-contract/.github
      - enterprise-contract/github-workflows
      - enterprise-contract/go-gather
      - enterprise-contract/golden-container
      - enterprise-contract/hacks
      - enterprise-contract/hooks
      - enterprise-contract/infra-deployments-ci
      - enterprise-contract/policy_builder
      - enterprise-contract/review-rot
      - enterprise-contract/tekton-catalog
      - enterprise-contract/user-guide
      - konflux-ci/build-definitions
      - konflux-ci/build-trusted-artifacts
      - konflux-ci/docs
      - konflux-ci/e2e-tests
      - konflux-ci/konflux-ci.github.io
      - konflux-ci/konflux-test
      - konflux-ci/release-service-catalog
      - redhat-appstudio/infra-deployments
      - redhat-appstudio/tssc-sample-templates
      - tektoncd/chains
    token: "${GITHUB_TOKEN}"
    type: github
